In [1]:
import torch

In [2]:
x = torch.rand(4,4)
print(x)

tensor([[0.9150, 0.9315, 0.2737, 0.8305],
        [0.6078, 0.6331, 0.2429, 0.3238],
        [0.6537, 0.7663, 0.2628, 0.0746],
        [0.1676, 0.9368, 0.4991, 0.9050]])


In [7]:
y = x.view(-1, 8) # this is basically resize

In [8]:
print(y)

tensor([[0.9150, 0.9315, 0.2737, 0.8305, 0.6078, 0.6331, 0.2429, 0.3238],
        [0.6537, 0.7663, 0.2628, 0.0746, 0.1676, 0.9368, 0.4991, 0.9050]])


In [41]:
a = torch.rand(3, requires_grad=True)
print(a)

d = a.detach()  # detach enables us to copy the tensor without the requires_grad
print(d)

# another option to disable the back propogation function to be true
with torch.no_grad():
    d = a*2

print(d)

tensor([0.4436, 0.0100, 0.0522], requires_grad=True)
tensor([0.4436, 0.0100, 0.0522])
tensor([0.8872, 0.0200, 0.1044])


b = a + 2
print(b)

c = b*b*2
print(c)

c = c.mean()
print(c)

In [34]:
c.backward()
print(a.grad)

tensor([3.6388, 3.8847, 3.8776])


In [57]:
weights = torch.ones(4, requires_grad=True)
print(weights, "\n")

for epoch in range(4):
    model_output = (weights*3).sum()
    print(model_output)
    model_output.backward()
    print(model_output)
    print(weights.grad, "\n")
    # need to reset weights
    
    weights.grad.zero_()

tensor([1., 1., 1., 1.], requires_grad=True) 

tensor(12., grad_fn=<SumBackward0>)
tensor(12., grad_fn=<SumBackward0>)
tensor([3., 3., 3., 3.]) 

tensor(12., grad_fn=<SumBackward0>)
tensor(12., grad_fn=<SumBackward0>)
tensor([3., 3., 3., 3.]) 

tensor(12., grad_fn=<SumBackward0>)
tensor(12., grad_fn=<SumBackward0>)
tensor([3., 3., 3., 3.]) 

tensor(12., grad_fn=<SumBackward0>)
tensor(12., grad_fn=<SumBackward0>)
tensor([3., 3., 3., 3.]) 



In [59]:
weights = torch.ones(4, requires_grad=True)
print(weights, "\n")

# optimizer
optimizer = torch.optim.SGD(weights, lr=0.01)
optimizer.step()
optimizer.zero_grad()


tensor([1., 1., 1., 1.], requires_grad=True) 



TypeError: params argument given to the optimizer should be an iterable of Tensors or dicts, but got torch.FloatTensor