In [3]:
import torch
import numpy as np

In [13]:
# Tensors can be created directly from data. The data type is automatically inferred.
data = [[1,2], [3,4]]
x_data = torch.tensor(data)
print(x_data, type(x_data))

tensor([[1, 2],
        [3, 4]]) <class 'torch.Tensor'>


In [16]:
# Tensors can be created from NumPy arrays (and vice versa - see Bridge with NumPy).
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np, type(x_np))

tensor([[1, 2],
        [3, 4]]) <class 'torch.Tensor'>


In [17]:
# From another tensor:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.8848, 0.0540],
        [0.7194, 0.7316]]) 



In [29]:
# Tensor attributes describe their shape, datatype, and the device on which they are stored.
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(type(tensor)) # I added just to compare
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
<class 'torch.Tensor'>
Device tensor is stored on: cpu


In [30]:
# We move our tensor to the GPU if available
print(torch.cuda.is_available())
if torch.cuda.is_available():
  tensor = tensor.to('cuda')
print(f"Device tensor is stored on: {tensor.device}")

False
Device tensor is stored on: cpu


In [56]:
#Standard numpy-like indexing and slicing:
tensor = torch.ones(4, 4)
tensor[:,1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [37]:
# Joining tensors You can use torch.cat to concatenate a sequence of tensors 
# along a given dimension. See also torch.stack, another tensor joining op that 
# is subtly different from torch.cat.
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [61]:
tensor1 = torch.clone(tensor)
tensor1[:, 2] = 3
tensor1[3, :] = 5
tensors = [tensor, tensor1, tensor1]
torch.stack(tensors, dim=1, out=None)

tensor([[[1., 0., 1., 1.],
         [1., 0., 3., 1.],
         [1., 0., 3., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 3., 1.],
         [1., 0., 3., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 3., 1.],
         [1., 0., 3., 1.]],

        [[1., 0., 1., 1.],
         [5., 5., 5., 5.],
         [5., 5., 5., 5.]]])

In [64]:
# Multiplying tensors
# This computes theelement-wise product
print(f"tensor.mul(tensor) \n {tensor1.mul(tensor1)} \n")
# Alternative syntax:
print(f"tensor * tensor \n {tensor1 * tensor1}")

tensor.mul(tensor) 
 tensor([[ 1.,  0.,  9.,  1.],
        [ 1.,  0.,  9.,  1.],
        [ 1.,  0.,  9.,  1.],
        [25., 25., 25., 25.]]) 

tensor * tensor 
 tensor([[ 1.,  0.,  9.,  1.],
        [ 1.,  0.,  9.,  1.],
        [ 1.,  0.,  9.,  1.],
        [25., 25., 25., 25.]])


In [87]:
# Reset the tensor
tensor = torch.ones_like(tensor)
tensor[:,1] = 0

# In-place operations Operations that have a _ suffix are in-place. 
# For example: x.copy_(y), x.t_(), will change x.
print(tensor, "\n")
print(tensor.add(5))
print(tensor, "\n")

print(tensor, "\n")
print(tensor.add_(5))
print(tensor, "\n")

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])
tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]]) 



In [88]:
# Tensors on the CPU and NumPy arrays can share their underlying memory locations, 
# and changing one will change the other.

t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]
